### ISSUE TITLE
New instrument request: ncas-cam-12

### ISSUE THREAD

**Issue by lecjlg** [ncasuk/ncas-data-instrument-vocabs#1]
### Instrument Manufacturer

Canon

### Instrument Model

EOS 6D Mark II

### Instrument Serial Number

583053001033

### Instrument Scientist Name

James Groves

### Instrument Scientist ORCID

https://orcid.org/0000-0002-7073-2085

### Instrument Owner (and ROR ID)

National Centre for Atmospheric Science (https://ror.org/01wwwe276)

### NCAS Observatory

mobile

### Instrument description

The Instrument is part of an automated camera system built to enable a better understanding of how cloud formations develop. . Each camera system has: a Canon EOS 6D Mark II camera, a UV lens filter, a Raspberry Pi, a Mikrotik Wifi transmitter/receiver, an 8Gb SD card and a 2Tb External hard-disk. The camera had an f/1.8 50mm prime lens giving angles-of-view of 40º, 27º,46º in the horizontal, vertical, and diagonal respectively, captured within 6240 x 4160 pixels.

The timelapse images this system provides a useful perspective on the development of the clouds, and in addition can be used to estimate properties such as the height of cloud base and cloud top.

**Comment by joshua-hampton** [comment]
This camera has been designated as camera 12. So, easy ones first:
NCAS instrument ID: ncas-cam-12
Instrument descriptor: NCAS Camera unit 12
Instrument category: imager
Host institution: Leeds

Data product - currently in the vocabs, all cameras are listed with product as `images - data product not defined`. However, the NCAS-IMAGE standard has since been defined, and is introducing products "photo" and "plot" (I think that's what they're called). So I would suggest using "photo" as the data product for this camera and work on switching other cameras over too.

**Comment by gap736uk** [comment]
@joshua-hampton  - I think the last point you make regarding switching all cameras over to the new data product in v1.1 of NCAS-Image is something that we need to take to @dahooper as a case in point for community engagement. Having the list of instruments that fall into this scope is a good starting point for Davey to message and get agreement on. We should be clear what v1.0 compliant files do and what v1.1 do.

**Comment by gap736uk** [comment]
@joshua-hampton  - isn't instrument descriptor done in lower case on the spreadsheet to be consistent with the other entries?

Last item of 'previous entries' should have _an_ entry even if 'none' to at least ensure that we have this field completed... though in due course we ought to drop this once we are sure we have completed this for all existing instruments. It's primary driver is to allow CEDA to track down all previous data from the instrument and link up within the archvie/cataloging.

**Comment by joshua-hampton** [comment]
> @joshua-hampton - isn't instrument descriptor done in lower case on the spreadsheet to be consistent with the other entries?

No, the format I wrote matches the format in the spreadsheet (i.e. every word starts with a capital except for "unit")

> Last item of 'previous entries' should have _an_ entry even if 'none' to at least ensure that we have this field completed... though in due course we ought to drop this once we are sure we have completed this for all existing instruments. It's primary driver is to allow CEDA to track down all previous data from the instrument and link up within the archvie/cataloging.

Currently these are just empty in the spreadsheet, and the downloader copes with that.

**Comment by gap736uk** [comment]
Thanks for confirming the descriptor field formatting.

Re the empty cells for previous identifiers. I think it is best to be explicit where possible as to what the status is:

1. an entry = previous IDs have been found and connections will be made in the archive
2. a 'none' entry = a check has been made and no previous IDs have been found/it's a new instrument entirely and no previous data released therefore no archive linking to past data needed
3. a null field  = no entry has been made and decision/check is needed.

that way any time we/someone else goes back to this list they can always see what work remains to be done.

**Comment by gap736uk** [comment]
@lecjlg: Josh and I have looked over this request and believe we have settled on the various required fields. Are you happy with these before we move to adding them to the vocab?

**Comment by lecjlg** [comment]
Yes all good on this one thanks

**Comment by joshua-hampton** [comment]
Thanks @lecjlg

**Comment by joshua-hampton** [comment]
Instrument details added to vocab list
