### ISSUE TITLE
New instrument request: ncas-lidar-aerosol-1

### ISSUE THREAD

**Issue by gapintheclouds** [ncasuk/ncas-data-instrument-vocabs#11]
### Instrument Manufacturer

Cimel

### Instrument Model

CE376-GPN

### Instrument Serial Number

2102-029

### Instrument Scientist Name

Hugo Ricketts

### Instrument Scientist ORCID

0000-0002-1708-2431

### Instrument Owner (and ROR ID)

National Centre for Atmospheric Science (https://ror.org/01wwwe276)

### NCAS Observatory

mobile

### Instrument description

The lidar uses two lasers to vertically profile the atmosphere. The laser light is scattered by air molecules, aerosol and cloud particles. This scattered light is detected by a telescope. The collected data can be used to determine the location and intensity of aerosol and cloud. It can also distinguish between solid and liquid particles.

**Comment by gapintheclouds** [comment]
Possible suggestions:

- NCAS instrument ID: `ncas-lidar-aerosol-1`
- Instrument descriptor: `lidar`
- Data product(s): `aerosol-backscatter`, `depolarisation-ratio`, `cloud-base` are the ones I can think of to start with.
- Instrument category: `mobile`?
- Host institution: `University of Manchester`
- List of previous instrument IDs (if any): N/A

**Comment by joshua-hampton** [comment]
Happy with most of these, couple of changes:
* Instrument descriptor: This is the value for the "source" global attribute in the netCDF file, based on other instruments this should be "NCAS Lidar Aerosol unit 1"
* Instrument category: Other Lidars in the list come under the category of "profiler" - suggest the same here

**Comment by gapintheclouds** [comment]
Thanks.

- Can we go with "NCAS Aerosol Lidar unit 1" (same as the Doppler lidars) as this sounds nicer?
- "Profiler" works well. I'll take two!

**Comment by gap736uk** [comment]
Will accept these final suggested changes.

**Comment by joshua-hampton** [comment]
Added to spreadsheet, ready for next repository update.
