### ISSUE TITLE
Edit instrument request: ncas-radar-camra-1

### ISSUE THREAD

**Issue by longlostjames** [ncasuk/ncas-data-instrument-vocabs#12]
### Instrument

ncas-radar-camra-1

### Attribute

Data Product

### New value

source attribute should be "NCAS S-Band CAMRa Weather Radar unit 1"

### Reason

Currently incorrectly designated as an X-Band radar.

**Comment by gap736uk** [comment]
@joshua-hampton and @gap736uk reviewed and happy with change request.

**Comment by joshua-hampton** [comment]
Updated in spreadsheet, ready for next repository update.
