### ISSUE TITLE
New instrument request

### ISSUE THREAD

**Issue by joshua-hampton** [ncasuk/ncas-data-instrument-vocabs#13]
### Instrument Manufacturer

Gill

### Instrument Model

WindSonic Option 2

### Instrument Serial Number

unknown

### Instrument Scientist Name

Joshua Hampton

### Instrument Scientist ORCID

https://orcid.org/0000-0001-7430-8655

### Instrument Owner (and ROR ID)

National Centre for Atmospheric Science (https://ror.org/01wwwe276)

### NCAS Observatory

CVAO

### Instrument description

This is a 2D wind sonic anemometer mounted at the top of a 10 metre tower, outputting U and V wind speeds.

**Comment by joshua-hampton** [comment]
Suggestions
ID: ncas-sonic-6
Descriptor: NCAS Sonic Anemometer unit 6
Data product: mean-winds
Category: Winds
Host: Leeds
Previous IDs: none

**Comment by gap736uk** [comment]
looks good.
