### ISSUE TITLE
New instrument request: ncas-cam-11

### ISSUE THREAD

**Issue by lecjlg** [ncasuk/ncas-data-instrument-vocabs#2]
### Instrument Manufacturer

Canon

### Instrument Model

EOS 6D Mark II

### Instrument Serial Number

583053001031

### Instrument Scientist Name

James Groves

### Instrument Scientist ORCID

https://orcid.org/0000-0002-7073-2085

### Instrument Owner (and ROR ID)

National Centre for Atmospheric Science (https://ror.org/01wwwe276)

### NCAS Observatory

mobile

### Instrument description

The Instrument is part of an automated camera system built to enable a better understanding of how cloud formations develop. . Each camera system has: a Canon EOS 6D Mark II camera, a UV lens filter, a Raspberry Pi, a Mikrotik Wifi transmitter/receiver, an 8Gb SD card and a 2Tb External hard-disk. The camera had an f/1.8 50mm prime lens giving angles-of-view of 40º, 27º,46º in the horizontal, vertical, and diagonal respectively, captured within 6240 x 4160 pixels.

The timelapse images this system provides a useful perspective on the development of the clouds, and in addition can be used to estimate properties such as the height of cloud base and cloud top.

**Comment by gap736uk** [comment]
@lecjlg: Josh and I have looked over this request and believe we have settled on the various required fields. Are you happy with these before we move to adding them to the vocab?

**Comment by lecjlg** [comment]
Yes all fine. thank you

**Comment by joshua-hampton** [comment]
Instrument details added to vocab list
