### ISSUE TITLE
New instrument request: ncas-radar-x-band-2

### ISSUE THREAD

**Issue by drlindsaybennett** [ncasuk/ncas-data-instrument-vocabs#3]
### Instrument Manufacturer

LEONARDO Germany GmbH

### Instrument Model

Meteor 60DX10-S

### Instrument Serial Number

2208392

### Instrument Scientist Name

Dr Lindsay Bennett

### Instrument Scientist ORCID

https://orcid.org/0000-0002-2451-1185

### Instrument Owner (and ROR ID)

University of Leeds (https://ror.org/024mrxd33)

### NCAS Observatory

mobile

### Instrument description

This is a radar that operates at X-band (9.320 GHz, 3cm) and has Doppler and dual-polarisation capability. The radar measures areal precipitation, radial winds and polarisation parameters. It can also detect clear-air echoes at close range from insects. The system has a conventional parabolic antenna of 2.4m diameter and a beamwidth of 1 degree. It is container-based, so it can be deployed at different locations.

**Comment by joshua-hampton** [comment]
This instrument is `ncas-radar-x-band-2`

**Comment by gap736uk** [comment]
Areas to discuss further: 
 - Instrument descriptor: NCAS X-Band Mobile Radar unit 2
Do we want to mirror the previous instrument (unit1) and include 'mobile'. 
The other cases:
ncas-mobile-ka-band-radar-1: NCAS Ka-Band Mobile Cloud Radar unit 1
ncas-mobile-x-band-radar-1: NCAS X-Band Mobile Radar unit 1
ncas-radar-wind-profiler-1: NCAS Mobile Radar Wind Profiler unit 1

Given that the last one is ceasing operation, but has the 'use' implied by the 'wind profiler' cf with the band reference, suggest following the precedent of the other 2 established ''-band mobile radar. (though the use of Cloud Radar). So suggest, in future, we have : <Owning institute> <band>-band <specifier> Radar unit #  ; where specifier would be something like mode of operation (mobile) when not fixed. Where mobile = re-deployable to any given platform (inc mobile platforms); airborne/shipborne for those that are permanently deployed for operation on a moving platform.


Data product(s): radar
This is as given at present. Needs defining against the NCAS-Radar standard (@longlostjames needed here to define these)

Host institution: University of Leeds
(@drlindsaybennett  - is this correct?)

**Comment by drlindsaybennett** [comment]
I hadn't realised the descriptor is a predefined thing. I thought it was something I could choose (not to blame Chris but his notes for the radar standard don't explicitly say it being predefined). So for the old radar it has always been "Leonardo Germany GmbH 50DX Mobile X-band Radar" and for the new radar I have used "Leonardo Germany GmbH 60DX10-S X-band Radar". But I see now that those names don't uniquely define either radar, however the global attributes do have serial numbers. 

Josh has also just brought it to my attention that we should have discussed and created the platform names with you, before populating our metadata. Informally in the group, Phil, Hugo and I decided to use platform = "mod-lyneham-woest-site-1"  (where xband1 was located) and platform = "mod-lyneham-woest-site-2" (where Kepler was located).  I discussed with Chris that this would make the filenames too long, so I have used just mod-lyneham for xband1 and for xband2 platform = "chilbolton-atmospheric-observatory" but in the filename I have shortened this to just "cao".

So it seems like some things need to be decided on and then I'll need to reprocess my files with the new metadata.

Re institution, I'm not totally clear on what defines a host institution, I would say yes it is University of Leeds. It is legally owned by Leeds and I am based at Leeds. Even though it's currently hosted at Chilbolton.

**Comment by drlindsaybennett** [comment]
Also forgot to say that I think the filenames should definitely be ncas-radar but the descriptor does make more sense to say NCAS X-band Radar Unit 2.......if the descriptor is how one would describe it out loud to another person then that makes sense as you wouldnt say NCAS Radar X-band.....but it all depends on what the definition and purpose of the descriptor is..
Sorry I'm not being very helpful really.

**Comment by gap736uk** [comment]
@drlindsaybennett when you say:

> Also forgot to say that I think the filenames should definitely be ncas-radar 

Are you advocating for these to be _just_ `ncas-radar` as the instrument identifier or flagging that you're happy that these are _starting_ with `ncas-radar` (i.e. what we've put as `ncas-radar-x-band-2` is good, you were just agreeing how it should start as opposed to the other options looked at?

Regarding platform... If one site was Chilbolton Observatory, then `cao` should be used. For other non-NCAS observatory sites then there is a way to check what site identifiers we already have, but I'm happy to check other suggestions ahead of creating files. The key thing here is that we're using _an_ identifier that we can then associate with some site metadata elsewhere.

At present there isn't really a Permanent Identifier (PIDs) scheme that we're using for platforms other than a list that we've been maintaining in CEDA over the years.  Hopefully, in due course, we can have more established PIDs for this type of information (so would be more universally understood e.g. by machines to pull back info and find other related information) but until then this is what we have...

**Comment by drlindsaybennett** [comment]
Yes to the first question, agreeing that ncas-radar-x-band-2 is good.

I don't think MOD Lyneham is already a site/platform in CEDA is it? So we'll need to create one.

**Comment by gap736uk** [comment]
MOD Lyneham platform record: https://catalogue.ceda.ac.uk/uuid/d08d1f4756e145a8a35ba8aba77a713e

**Comment by gap736uk** [comment]
@drlindsaybennett  - Josh and I have discussed this and, comparing it with other instruments, we believe this corresponds to the institute that manages the instrument on a day-to-day basis (e.g. who do you arrange the insurance/purchase replacement parts through etc).  So we think this is the `University of Leeds` in this case.

**Comment by joshua-hampton** [comment]
Instrument details added to vocab list
